export const CHANGE_TREATMENT_FIELD = 'CHANGE_TREATMENT_FIELD';
export const CHANGE_LOCATION_FIELD = 'CHANGE_LOCATION_FIELD';
export const CHANGE_DATE_FIELD = 'CHANGE_DATE_FIELD';
export const CHANGE_START_HOUR_FIELD = 'CHANGE_START_HOUR_FIELD';
export const CHANGE_END_HOUR_FIELD = 'CHANGE_END_HOUR_FIELD';
export const CHANGE_TIME_FIELD = 'CHANGE_TIME_FIELD';
export const HIDE_MAP_FIELD = 'HIDE_MAP_FIELD';
export const SHOW_CARDS_FIELD = 'SHOW_CARDS_FIELD';